name: Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello Nadeem! GitHub Actions is working 🚀"

      - name: Show files
        run: ls -la
