---
on:
    pull_request:
        branches: 
            - dev

jobs:
    learning:
        runs-on: ubuntu-latest
        steps:
            - name: learning
              run: "echo hello how are you "
            - name: list env
              run: printenv