---
on:
    pull_request:
        branches: 
            - dev

jobs:
    exercise4:
        runs-on: ubuntu-latest
        steps:
            - name: exercise4
              run: "echo thanks  for sending changes"
            - name: list env
              run: printenv
